routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::match(['get','post'],'/login','AdminsController@login')->name('login');

Route::group(['middleware'=> 'admin.session'], function(){
    Route::prefix('/')->group(function(){
        Route::get('/','DashboardController@index')->name('dashboard');
        Route::get('/operations','OperationsController@index')->name('operations');
    
        Route::get('/daily_new/{d}/edit','DailyNewsController@edit');
        Route::post('/daily_new/{d}/edit','DailyNewsController@update');
    
        Route::prefix('operations')->group(function(){
            Route::get('/','OperationsController@index')->name('operations');
            Route::get('/create','OperationsController@create')->name('create_operation');
            Route::post('/store','OperationsController@store')->name('store_operation');
            Route::get('/{id}','OperationsController@edit')->name('operations.edit');
            Route::put('/{id}','OperationsController@update')->name('operations.update');
            Route::delete('/{id}','OperationsController@destroy')->name('operations.destroy');
        });
    
        Route::resource('dailytips','DailyTipsController');

        Route::resource('dailytipsprofits','DailytipsProfitController');

        Route::get('/dailytipsexport','DailyTipsController@export')->name('dailytips.export');
    
        Route::resource('livetradings','LiveTradingsController');
    
        Route::resource('operations_history','OperationsHistoryController');
    
        Route::resource('next_live','NextLiveController');
    
        Route::resource('week_class','WeekClassController');

        Route::resource('big_week_class','BigWeekClassController');
    
        Route::resource('official_notice','OfficialNoticeController');

        Route::resource('dailytips_notice','DailyTipNoticesController');

        Route::get('/dailytips_notice/deactivate/{id}','DailyTipNoticesController@deactivate')->name('deactivate_dailytips_notice');
    
        Route::get('/official_notice/deactivate/{id}','OfficialNoticeController@deactivate')->name('deactivate_official_notice');

        Route::resource('modules','ModulesController');

        Route::prefix('questions')->group(function(){
            Route::get('/{module}','ModuleQuestionsController@index')->name('questions.index');
            Route::get('/{module}/create','ModuleQuestionsController@create')->name('questions.create');
            Route::post('/{module}','ModuleQuestionsController@store')->name('questions.store');
            Route::get('/{question}/edit','ModuleQuestionsController@edit')->name('questions.edit');
            Route::put('/{question}','ModuleQuestionsController@update')->name('questions.update');
            Route::delete('/{question}','ModuleQuestionsController@destroy')->name('questions.destroy');
        });

        Route::prefix('answers')->group(function(){
            Route::get('/{question}','AnswersController@index')->name('answers.index');
            Route::get('/{question}/create','AnswersController@create')->name('answers.create');
            Route::post('/{question}','AnswersController@store')->name('answers.store');
            Route::get('/{answer}/edit','AnswersController@edit')->name('answers.edit');
            Route::put('/{answer}','AnswersController@update')->name('answers.update');
            Route::delete('/{answer}','AnswersController@destroy')->name('answers.destroy');
        });

        Route::resource('modals','ModalsController');

        Route::get('/modals/deactivate/{id}','ModalsController@deactivate')->name('deactivate_modal');

        Route::prefix('modulevideos')->group(function(){
            Route::get('/{module}','ModuleVideosController@index')->name('modulevideos.index');
            Route::get('/{module}/create','ModuleVideosController@create')->name('modulevideos.create');
            Route::post('/{module}','ModuleVideosController@store')->name('modulevideos.store');
            Route::get('/{modulevideo}/edit','ModuleVideosController@edit')->name('modulevideos.edit');
            Route::delete('/{modulevideo}','ModuleVideosController@destroy')->name('modulevideos.destroy');
            Route::put('/{modulevideo}','ModuleVideosController@update')->name('modulevideos.update');
        });

        Route::resource('{module_id}/pdf','PdfModulesController');
        Route::resource('languages','StringLanguagesController');

        Route::prefix('contentstrings')->group(function(){
            Route::post("/",'ContentStringsController@store')->name('contentstrings.store');
        });

        Route::resource('nextophistory','NextOpHistoryController');

        Route::resource('tickets','TicketsController');
        Route::get('tickets/close/{id}','TicketsController@close')->name('close_ticket');
        Route::get('/tickets/hide/{id}','TicketsController@hide')->name('hide_ticket');

        Route::resource('ticketmessages','TicketMessagesController');

        Route::resource('noticevideos','DailyTipNoticeVideosController');

        Route::get('/noticevideos/deactivate/{id}','DailyTipNoticeVideosController@deactivate')->name('deactivate_noticevideo');

        Route::resource('bigbets','BigBetsController');

        Route::resource('racingtracks','RacingTracksController');

        Route::resource('horses','HorsesController');

        Route::resource('livehorses','LiveHorsesController');

        Route::resource('distances','DistancesController');

        Route::resource('analysis','AnalysisController');

        Route::resource('analysistips','AnalysisTipsController');

        Route::get('/validatetip/{id}','AnalysisTipsController@validateTip')->name('validatetip');

        Route::resource('classes','AnalysisClassesController');

        Route::resource('chats','Chat\ChatsController');

        Route::get('analysisvalidated','AnalysisValidatedController@index')->name('analysisvalidated');

        Route::resource('horsepositions','HorsePositionsController');

        Route::resource('usertests','UserTestsController');

        // Route::get('/{chat_id}/messages','Chat\MessagesController@fetch');
        // Route::post('/{chat_id}/messages','Chat\MessagesController@sentMessage');

        Route::resource('tipstar','TipStarsController');
        Route::resource('racingtracksguides','RacingTrackGuidesController');

        Route::prefix('systeminfo')->group(function(){
            Route::get('/{key}','SystemInfosController@show');
            Route::put('/', 'SystemInfosController@update')->name('systeminfo.update');
        });

        Route::resource('startipvideos','StarTipVideosController');

        Route::resource('avulsevideos','AvulseVideosController');

        Route::resource('startipsprofits', 'StarTipsProfitsController');
    });
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Module;
use App\Model\Ticket;
use App\User;
use App\Model\LiveTrading;
use App\Model\UserTest;
use App\Model\TipStar;

class DashboardController extends Controller
{
    public function index(){
        $active_modules = Module::active()->count();
        $total_modules = Module::count();
        $open_tickets = Ticket::open()->count();
        $total_tickets = Ticket::count();
        $last_tickets = Ticket::orderBy('id','DESC')->limit(5)->get();
        $total_users = User::count();
        $last_live_trading = LiveTrading::latest()->first();
        $users_on_modules = Module::usersOnModules();
        $last_tests = UserTest::latest()->limit(7)->get();
        $tipstars = TipStar::fromToday()->count();
        $total_tipstars = TipStar::count();
        
        return View('dashboard.index')
                ->with('active_modules',$active_modules)
                ->with('total_modules',$total_modules)
                ->with('open_tickets',$open_tickets)
                ->with('total_tickets',$total_tickets)
                ->with('last_tickets',$last_tickets)
                ->with('total_users', $total_users)
                ->with('last_live_trading',$last_live_trading)
                ->with('users_on_modules', $users_on_modules)
                ->with('last_tests', $last_tests)
                ->with('tipstars' , $tipstars)
                ->with('total_tipstars', $total_tipstars);
    }
}

resources/views/dashboard/index.blade.php
@extends('layout.panel')

@section('content')

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">

<style>
    .videoWrapper {
        position: relative;
        padding-bottom: 56.25%; /* 16:9 */
        padding-top: 25px;
        height: 0;
    }
    .videoWrapper iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
</style>

<div class="content-main " id="content-main">
  <div class="padding">
    <div class="row">
      <div class="col-lg-12">
        @if(Session::has('success'))
          <div class="alert green">
            <b>{{Session::get('success')}}</b>
          </div>
        @endif
        @if(Session::has('error'))
          <div class="alert green">
            <b>{{Session::get('error')}}</b>
          </div>
        @endif
      </div>
    </div>
    <div class="row align-items-stretch">
      <div class="col-lg-3">
          <div class="box list-item">
            <!-- <span class="avatar w-40 text-center rounded success">
              <span class="fa fa-users"></span>
            </span> -->
            <span class="avatar w-40 text-center text-success">
              <i class="fa fa-users"></i>
            </span>
            <div class="list-body">
              <h4 class="m-0 text-md">
                <a href="#">{{$total_users}} <span class="text-sm">Alunos</span></a>
              </h4>
            </div>
          </div>
      </div>
      <div class="col-lg-3">
          <div class="box list-item">
            <!-- <span class="avatar w-40 text-center rounded primary">
              <span class="fas fa-calendar-alt"></span>
            </span> -->
            <span class="avatar w-40 text-primary text-center">
              <i class="fas fa-calendar-alt"></i>
            </span>
            <div class="list-body">
              <h4 class="m-0 text-md">
                <a href="{{route('modules.index')}}">{{$active_modules}} <span class="text-sm">Módulos ativos</span></a>
              </h4>
              <small class="text-muted">{{$total_modules}} total</small>
            </div>
          </div>
      </div>
      <div class="col-lg-3">
          <div class="box list-item">
            <!-- <span class="avatar w-40 text-center rounded warning"> -->
            <span class="avatar text-warning w-40 text-center">
              <i class="fas fa-headset"></i>
            </span>
            <!-- </span> -->
            <div class="list-body">
              <h4 class="m-0 text-md">
                <a href="{{route('tickets.index')}}">{{$open_tickets}} <span class="text-sm">Tickets aguardando</span></a>
              </h4>
              <small class="text-muted">{{$total_tickets}} total</small>
            </div>
          </div>
      </div>
      <div class="col-lg-3">
        <div class="box list-item">
          <!-- <span class="avatar w-40 text-center rounded warning"> -->
          <span class="avatar w-40 text-center" style="color: #49cece !important;">
            <i class="fas fa-star"></i>
          </span>
          <!-- </span> -->
          <div class="list-body">
            <h4 class="m-0 text-md">
              <a href="{{route('tipstar.index')}}">{{$tipstars}} <span class="text-sm">Tips Stars hoje</span></a>
            </h4>
            <small class="text-muted">{{$total_tipstars}} total</small>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-7">
          <div class="box">
              <div class="box-header"><h3>Alunos por modulo</h3></div>
              <div class="box-body p-0">
                <input type="hidden" name="users_modules" value="{{$users_on_modules->toJson()}}">
                <div id="users_module_canvas"></div>
              </div>
          </div>
      </div>
      <div class="col-lg-5">
        <div class="box">
          <div class="box-header">
            <h3>Ultimas provas</h3>
          </div>
          <div class="box-tool">
            <a href="{{route('usertests.index')}}" class="btn btn-primary btn-xs">Ver todos</a>
          </div>
          <div class="box-body table p-0">
            <table class="table table-hover">
              <thead>
                <th>Usuario</th>
                <th class="text-center">Módulo</th>
                <th class="text-center">Nota</th>
                <th class="text-center">Aprovado</th>
              </thead>
              <tbody>
                @foreach($last_tests as $test)
                <tr>
                  <td>{{$test->user->firstName()}}</td>
                  <td class="text-center">{{$test->module->title}}</td>
                  <td class="text-center">{{$test->decimalGrade()}}</td>
                  <td class="text-center">{!!$test->approved? '<span class="badge badge-success">Sim</span>' : '<span class="badge badge-danger">Não</span>'!!}</td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="row align-items-stretch">
      <div class="col-lg-6">
          <div class="box">
            <div class="box-header"><h3>Últimos tickets</h3></div>
            <div class="box-tool">
              <a href="{{route('tickets.index')}}" class="btn btn-primary btn-xs">Ver todos</a>
            </div>
            <div class="list inset">
              @foreach($last_tickets as $ticket)
                <div class="list-item" data-id="item-9">
                  
                    <div class="list-body">
                      <a class="item-title _500">{{$ticket->user->name}} - <small>{{$ticket->created_at}}</small></a>
                      <div class="item-except text-sm text-muted h-1x">{{$ticket->title}}</div>
                    </div>
                    <div>
                        <div class="item-action">
                          <a href="{{route('tickets.show',['id'=>$ticket->id])}}" class="btn primary" aria-expanded="false">
                            <i class="fa fa-comment"></i>
                          </a>
                        </div>
                    </div>
                </div>
              @endforeach
            </div>
          </div>
          
      </div>
      <div class="col-lg-6">
        <div class="box">
          <div class="box-header">
            <h3>Última Live</h3>
            <small>{{$last_live_trading->title}}</small>
          </div>
          <div class="box-tool">
              <a href="{{route('next_live.index')}}" class="btn btn-primary btn-xs">Próxima live</a>
            </div>
          <div class="list-body">
            <div class="videoWrapper">                                    
              <iframe width="100%" height="auto" src="{{$last_live_trading->url}}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection


@section('js')
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
<script type="text/javascript">
var earnings_graph = Morris.Area.prototype.fillForSeries = function (i) {
        var color;
        return "10-#b452c3-#49cece";
    };

    var users_modules_graph = JSON.parse($('input[name=users_modules]').val());
    Morris.Area({
      element:'users_module_canvas',
      pointSize:0,
      lineWidth:0,
      data:users_modules_graph,
      xkey:'module',
      ykeys:['amount'],
      labels:['Alunos'],
      resize:false,
      parseTime : false,
      hideHover:"auto",
      fillOpacity: 0.8,
      gridLineColor:"transparent"
    });
</script>
@endsection