routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::match(['get','post'],'/login','AdminsController@login')->name('login');

Route::group(['middleware'=> 'admin.session'], function(){
    Route::prefix('/')->group(function(){
        Route::get('/','DashboardController@index')->name('dashboard');
        Route::get('/operations','OperationsController@index')->name('operations');
    
        Route::get('/daily_new/{d}/edit','DailyNewsController@edit');
        Route::post('/daily_new/{d}/edit','DailyNewsController@update');
    
        Route::prefix('operations')->group(function(){
            Route::get('/','OperationsController@index')->name('operations');
            Route::get('/create','OperationsController@create')->name('create_operation');
            Route::post('/store','OperationsController@store')->name('store_operation');
            Route::get('/{id}','OperationsController@edit')->name('operations.edit');
            Route::put('/{id}','OperationsController@update')->name('operations.update');
            Route::delete('/{id}','OperationsController@destroy')->name('operations.destroy');
        });
    
        Route::resource('dailytips','DailyTipsController');

        Route::resource('dailytipsprofits','DailytipsProfitController');

        Route::get('/dailytipsexport','DailyTipsController@export')->name('dailytips.export');
    
        Route::resource('livetradings','LiveTradingsController');
    
        Route::resource('operations_history','OperationsHistoryController');
    
        Route::resource('next_live','NextLiveController');
    
        Route::resource('week_class','WeekClassController');

        Route::resource('big_week_class','BigWeekClassController');
    
        Route::resource('official_notice','OfficialNoticeController');

        Route::resource('dailytips_notice','DailyTipNoticesController');

        Route::get('/dailytips_notice/deactivate/{id}','DailyTipNoticesController@deactivate')->name('deactivate_dailytips_notice');
    
        Route::get('/official_notice/deactivate/{id}','OfficialNoticeController@deactivate')->name('deactivate_official_notice');

        Route::resource('modules','ModulesController');

        Route::prefix('questions')->group(function(){
            Route::get('/{module}','ModuleQuestionsController@index')->name('questions.index');
            Route::get('/{module}/create','ModuleQuestionsController@create')->name('questions.create');
            Route::post('/{module}','ModuleQuestionsController@store')->name('questions.store');
            Route::get('/{question}/edit','ModuleQuestionsController@edit')->name('questions.edit');
            Route::put('/{question}','ModuleQuestionsController@update')->name('questions.update');
            Route::delete('/{question}','ModuleQuestionsController@destroy')->name('questions.destroy');
        });

        Route::prefix('answers')->group(function(){
            Route::get('/{question}','AnswersController@index')->name('answers.index');
            Route::get('/{question}/create','AnswersController@create')->name('answers.create');
            Route::post('/{question}','AnswersController@store')->name('answers.store');
            Route::get('/{answer}/edit','AnswersController@edit')->name('answers.edit');
            Route::put('/{answer}','AnswersController@update')->name('answers.update');
            Route::delete('/{answer}','AnswersController@destroy')->name('answers.destroy');
        });

        Route::resource('modals','ModalsController');

        Route::get('/modals/deactivate/{id}','ModalsController@deactivate')->name('deactivate_modal');

        Route::prefix('modulevideos')->group(function(){
            Route::get('/{module}','ModuleVideosController@index')->name('modulevideos.index');
            Route::get('/{module}/create','ModuleVideosController@create')->name('modulevideos.create');
            Route::post('/{module}','ModuleVideosController@store')->name('modulevideos.store');
            Route::get('/{modulevideo}/edit','ModuleVideosController@edit')->name('modulevideos.edit');
            Route::delete('/{modulevideo}','ModuleVideosController@destroy')->name('modulevideos.destroy');
            Route::put('/{modulevideo}','ModuleVideosController@update')->name('modulevideos.update');
        });

        Route::resource('{module_id}/pdf','PdfModulesController');
        Route::resource('languages','StringLanguagesController');

        Route::prefix('contentstrings')->group(function(){
            Route::post("/",'ContentStringsController@store')->name('contentstrings.store');
        });

        Route::resource('nextophistory','NextOpHistoryController');

        Route::resource('tickets','TicketsController');
        Route::get('tickets/close/{id}','TicketsController@close')->name('close_ticket');
        Route::get('/tickets/hide/{id}','TicketsController@hide')->name('hide_ticket');

        Route::resource('ticketmessages','TicketMessagesController');

        Route::resource('noticevideos','DailyTipNoticeVideosController');

        Route::get('/noticevideos/deactivate/{id}','DailyTipNoticeVideosController@deactivate')->name('deactivate_noticevideo');

        Route::resource('bigbets','BigBetsController');

        Route::resource('racingtracks','RacingTracksController');

        Route::resource('horses','HorsesController');

        Route::resource('livehorses','LiveHorsesController');

        Route::resource('distances','DistancesController');

        Route::resource('analysis','AnalysisController');

        Route::resource('analysistips','AnalysisTipsController');

        Route::get('/validatetip/{id}','AnalysisTipsController@validateTip')->name('validatetip');

        Route::resource('classes','AnalysisClassesController');

        Route::resource('chats','Chat\ChatsController');

        Route::get('analysisvalidated','AnalysisValidatedController@index')->name('analysisvalidated');

        Route::resource('horsepositions','HorsePositionsController');

        Route::resource('usertests','UserTestsController');

        // Route::get('/{chat_id}/messages','Chat\MessagesController@fetch');
        // Route::post('/{chat_id}/messages','Chat\MessagesController@sentMessage');

        Route::resource('tipstar','TipStarsController');
        Route::resource('racingtracksguides','RacingTrackGuidesController');

        Route::prefix('systeminfo')->group(function(){
            Route::get('/{key}','SystemInfosController@show');
            Route::put('/', 'SystemInfosController@update')->name('systeminfo.update');
        });

        Route::resource('startipvideos','StarTipVideosController');

        Route::resource('avulsevideos','AvulseVideosController');

        Route::resource('startipsprofits', 'StarTipsProfitsController');
    });
});

app/Http/Controllers/DailytipsProfitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\DailytipsProfit;
use App\Model\DailytipType;
use Validator;

class DailytipsProfitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dailytipsprofits = DailytipsProfit::orderBy('due_date','DESC')->paginate(15);

        return View('dailytipsprofits.index')->with('dailytipsprofits', $dailytipsprofits);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = DailytipType::get();
        return View('dailytipsprofits.create')->with('types',$types);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = Validator::make($request->all(),[
            'dailytips_types_id' => 'required',
            'profit' => 'required',
            'due_date' => 'required'
        ]);

        if($validation->fails()){
            return back()->with('error', $validation->errors()->all()[0]);
        }
        else{
            $dailytip_profit = new DailytipsProfit;
            $dailytip_profit->due_date = $request->input('due_date');
            $dailytip_profit->profit = $request->input('profit');
            $dailytip_profit->accumulated_profit = $request->has('accumulated_profit') ? $request->input('accumulated_profit') : null;
            $dailytip_profit->dailytips_types_id = $request->input('dailytips_types_id');
            $dailytip_profit->sent_tips = $request->has('sent_tips')? $request->input('sent_tips') : 0;
            $dailytip_profit->winner_tips = $request->has('winner_tips')? $request->input('winner_tips') : 0;
            $dailytip_profit->loose_tips = $request->has('loose_tips')? $request->input('loose_tips') : 0;

            $dailytip_profit->save();

            return redirect()->route('dailytipsprofits.index')->with('success','Lucro de tip salvo');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $profit = DailytipsProfit::find($id);
        $types = DailytipType::get();
        return View('dailytipsprofits.edit')->with('profit',$profit)->with('types', $types);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = Validator::make($request->all(),[
            'dailytips_types_id' => 'required',
            'profit' => 'required',
            'due_date' => 'required'
        ]);

        if($validation->fails()){
            return back()->with('error', $validation->errors()->all()[0]);
        }
        else{
            $dailytip_profit = DailytipsProfit::find($id);
            $dailytip_profit->due_date = $request->input('due_date');
            $dailytip_profit->profit = $request->input('profit');
            $dailytip_profit->dailytips_types_id = $request->input('dailytips_types_id');
            $dailytip_profit->accumulated_profit = $request->input('accumulated_profit');
            $dailytip_profit->sent_tips = $request->has('sent_tips')? $request->input('sent_tips') : 0;
            $dailytip_profit->winner_tips = $request->has('winner_tips')? $request->input('winner_tips') : 0;
            $dailytip_profit->loose_tips = $request->has('loose_tips')? $request->input('loose_tips') : 0;
            $dailytip_profit->save();

            return redirect()->route('dailytipsprofits.index')->with('success','Lucro de tip salvo');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DailytipsProfit::destroy($id);
        return redirect()->route('dailytipsprofits.index')->with('success','Lucro de tip removido');
    }
}

resources/views/dailytipsprofits/create.blade.php
@extends('layout.panel')

@section('content')
<div class="content-main " id="content-main">
  <div class="padding">
    @if(Session::has('error'))
      <div class="row">
        <div class="col-lg-12">
          <div class="alert alert-danger">{{Session::get('error')}}</div>
        </div>
      </div>
    @endif
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="box-header">
            <h2>Nova Lucro de tip</h2>
          </div>
          <div class="box-divider m-0"></div>
          <div class="box-body">
            <form action="{{route('dailytipsprofits.store')}}" method="post">
                {{ csrf_field() }}
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label>Dia</label>
                    <input type="date" class="form-control" name="due_date" id="due_date" placeholder="2018-03-12">
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label>Tipo</label>
                    <select class="form-control" name="dailytips_types_id">
                    @foreach($types as $type)
                      <option value="{{$type->id}}">{{$type->name}}</option>
                    @endforeach
                    </select>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label>Porcentagem (%)</label>
                    <input type="text" class="form-control" name="profit" id="profit" placeholder="12">
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label>Lucro acumulado (%)</label>
                    <input type="text" class="form-control" name="accumulated_profit" id="accumulated_profit" placeholder="12">
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>Tips distribuidas</label>
                    <input type="text" class="form-control" name="sent_tips" id="sent_tips" placeholder="1">
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>Tips vencedoras</label>
                    <input type="text" class="form-control" name="winner_tips" id="winner_tips" placeholder="1">
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>Tips perderoras</label>
                    <input type="text" class="form-control" name="loose_tips" id="loose_tips" placeholder="1">
                  </div>
                </div>
              </div>

              

              

              
              
              <button type="submit" class="btn primary">Salvar</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/dailytipsprofits/edit.blade.php
@extends('layout.panel')

@section('content')
<div class="content-main " id="content-main">
  <div class="padding">
    @if(Session::has('error'))
      <div class="row">
        <div class="col-lg-12">
          <div class="alert alert-danger">{{Session::get('error')}}</div>
        </div>
      </div>
    @endif
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="box-header">
            <h2>Nova Lucro de tip</h2>
          </div>
          <div class="box-divider m-0"></div>
          <div class="box-body">
            <form action="{{route('dailytipsprofits.update',['dailytipprofit'=>$profit->id])}}" method="post">
              <input type="hidden" name="_method" value="put">
                {{ csrf_field() }}
              <div class="form-group">
                <label>Dia</label>
                <input type="date" class="form-control" name="due_date" id="due_date" placeholder="2018-03-12" value="{{$profit->due_date}}">
              </div>

              <div class="form-group">
                <label>Tipo</label>
                <select class="form-control" name="dailytips_types_id">
                @foreach($types as $type)
                  <option value="{{$type->id}}" {{$type->id == $profit->dailytips_types_id? 'selected' : ''}}>{{$type->name}}</option>
                @endforeach
                </select>
              </div>

              <div class="form-group">
                <label>Porcentagem (%)</label>
              <input type="text" class="form-control" name="profit" id="profit" placeholder="12" value="{{$profit->profit}}">
              </div>

              <div class="form-group">
                <label>Lucro acumulado (%)</label>
                <input type="text" class="form-control" name="accumulated_profit" id="accumulated_profit" placeholder="12" value="{{$profit->accumulated_profit}}">
              </div>

              <div class="row">
                  <div class="col-lg-4">
                    <div class="form-group">
                      <label>Tips distribuidas</label>
                      <input type="text" class="form-control" name="sent_tips" id="sent_tips" placeholder="1" value="{{$profit->sent_tips}}">
                    </div>
                  </div>
                  <div class="col-lg-4">
                    <div class="form-group">
                      <label>Tips vencedoras</label>
                      <input type="text" class="form-control" name="winner_tips" id="winner_tips" placeholder="1" value="{{$profit->winner_tips}}">
                    </div>
                  </div>
                  <div class="col-lg-4">
                    <div class="form-group">
                      <label>Tips perderoras</label>
                      <input type="text" class="form-control" name="loose_tips" id="loose_tips" placeholder="1" value="{{$profit->loose_tips}}">
                    </div>
                  </div>
                </div>
              
              <button type="submit" class="btn primary">Atualizar</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/dailytipsprofits/index.blade.php
@extends('layout.panel')

@section('content')

<div class="content-main " id="content-main">
  <div class="padding">
  
    <div class="row">
      <div class="col-lg-12">
        @if(Session::has('success'))
          <div class="alert green">
            <b>{{Session::get('success')}}</b>
          </div>
        @endif
      </div>
    </div>

    <div class="row align-items-stretch">
      <div class="col-sm-12">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Plataforma do Professor</a></li>
          <li class="breadcrumb-item active">Lucro das tips</li></ol>
        <a href="{{route('dailytipsprofits.create')}}" class="btn btn-fw primary" style="margin-bottom: 40px;">
          <i class="fa fa-plus"></i> Adicionar Lucro de Tip</a>
        <table id="" class="table v-middle p-0 m-0 box dataTable no-footer" data-plugin="dataTable" role="grid" aria-describedby="datatable_info">
          <thead>
            <tr>
              <td align="center" style="font-weight: 900; border-bottom: 1px solid #11111124;">Dia</td>
              <td align="center" style="font-weight: 900; border-bottom: 1px solid #11111124;">Tipo</td>
              <td align="center" style="font-weight: 900; border-bottom: 1px solid #11111124;">Porcentagem</td>
              <td align="center" style="font-weight: 900; border-bottom: 1px solid #11111124;">Tips distribuidas</td>
              <td align="center" style="font-weight: 900; border-bottom: 1px solid #11111124;">Tips vencedoras</td>
              <td align="center" style="font-weight: 900; border-bottom: 1px solid #11111124;">Tips perderoras</td>
              <td align="center" style="font-weight: 900; border-bottom: 1px solid #11111124;"></td>
            </tr>
          </thead>
          <tbody>
            @foreach($dailytipsprofits as $profit)
              <tr>
                  <td align="center">{{$profit->due_date}}</td>
                  <td align="center">{{$profit->type->name}}</td>
                  <td align="center">{{$profit->profit}}</td>
                  <td align="center">{{$profit->sent_tips}}</td>
                  <td align="center">{{$profit->winner_tips}}</td>
                  <td align="center">{{$profit->loose_tips}}</td>
                  <td align="right">
                    <form action="{{route('dailytipsprofits.destroy',['profit'=>$profit->id])}}" method="post">
                      <input type="hidden" name="_method" value="delete">
                      {{csrf_field()}}
                      <a href="{{route('dailytipsprofits.edit',['id'=>$profit->id])}}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                      <button type="submit" class="btn btn-danger"><i class="fa fa-times"></i></button>
                    </form>
                  </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        {{$dailytipsprofits->links()}}
      </div>
    </div>
  </div>
</div>
@endsection