routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::match(['get','post'],'/login','AdminsController@login')->name('login');

Route::group(['middleware'=> 'admin.session'], function(){
    Route::prefix('/')->group(function(){
        Route::get('/','DashboardController@index')->name('dashboard');
        Route::get('/operations','OperationsController@index')->name('operations');
    
        Route::get('/daily_new/{d}/edit','DailyNewsController@edit');
        Route::post('/daily_new/{d}/edit','DailyNewsController@update');
    
        Route::prefix('operations')->group(function(){
            Route::get('/','OperationsController@index')->name('operations');
            Route::get('/create','OperationsController@create')->name('create_operation');
            Route::post('/store','OperationsController@store')->name('store_operation');
            Route::get('/{id}','OperationsController@edit')->name('operations.edit');
            Route::put('/{id}','OperationsController@update')->name('operations.update');
            Route::delete('/{id}','OperationsController@destroy')->name('operations.destroy');
        });
    
        Route::resource('dailytips','DailyTipsController');

        Route::resource('dailytipsprofits','DailytipsProfitController');

        Route::get('/dailytipsexport','DailyTipsController@export')->name('dailytips.export');
    
        Route::resource('livetradings','LiveTradingsController');
    
        Route::resource('operations_history','OperationsHistoryController');
    
        Route::resource('next_live','NextLiveController');
    
        Route::resource('week_class','WeekClassController');

        Route::resource('big_week_class','BigWeekClassController');
    
        Route::resource('official_notice','OfficialNoticeController');

        Route::resource('dailytips_notice','DailyTipNoticesController');

        Route::get('/dailytips_notice/deactivate/{id}','DailyTipNoticesController@deactivate')->name('deactivate_dailytips_notice');
    
        Route::get('/official_notice/deactivate/{id}','OfficialNoticeController@deactivate')->name('deactivate_official_notice');

        Route::resource('modules','ModulesController');

        Route::prefix('questions')->group(function(){
            Route::get('/{module}','ModuleQuestionsController@index')->name('questions.index');
            Route::get('/{module}/create','ModuleQuestionsController@create')->name('questions.create');
            Route::post('/{module}','ModuleQuestionsController@store')->name('questions.store');
            Route::get('/{question}/edit','ModuleQuestionsController@edit')->name('questions.edit');
            Route::put('/{question}','ModuleQuestionsController@update')->name('questions.update');
            Route::delete('/{question}','ModuleQuestionsController@destroy')->name('questions.destroy');
        });

        Route::prefix('answers')->group(function(){
            Route::get('/{question}','AnswersController@index')->name('answers.index');
            Route::get('/{question}/create','AnswersController@create')->name('answers.create');
            Route::post('/{question}','AnswersController@store')->name('answers.store');
            Route::get('/{answer}/edit','AnswersController@edit')->name('answers.edit');
            Route::put('/{answer}','AnswersController@update')->name('answers.update');
            Route::delete('/{answer}','AnswersController@destroy')->name('answers.destroy');
        });

        Route::resource('modals','ModalsController');

        Route::get('/modals/deactivate/{id}','ModalsController@deactivate')->name('deactivate_modal');

        Route::prefix('modulevideos')->group(function(){
            Route::get('/{module}','ModuleVideosController@index')->name('modulevideos.index');
            Route::get('/{module}/create','ModuleVideosController@create')->name('modulevideos.create');
            Route::post('/{module}','ModuleVideosController@store')->name('modulevideos.store');
            Route::get('/{modulevideo}/edit','ModuleVideosController@edit')->name('modulevideos.edit');
            Route::delete('/{modulevideo}','ModuleVideosController@destroy')->name('modulevideos.destroy');
            Route::put('/{modulevideo}','ModuleVideosController@update')->name('modulevideos.update');
        });

        Route::resource('{module_id}/pdf','PdfModulesController');
        Route::resource('languages','StringLanguagesController');

        Route::prefix('contentstrings')->group(function(){
            Route::post("/",'ContentStringsController@store')->name('contentstrings.store');
        });

        Route::resource('nextophistory','NextOpHistoryController');

        Route::resource('tickets','TicketsController');
        Route::get('tickets/close/{id}','TicketsController@close')->name('close_ticket');
        Route::get('/tickets/hide/{id}','TicketsController@hide')->name('hide_ticket');

        Route::resource('ticketmessages','TicketMessagesController');

        Route::resource('noticevideos','DailyTipNoticeVideosController');

        Route::get('/noticevideos/deactivate/{id}','DailyTipNoticeVideosController@deactivate')->name('deactivate_noticevideo');

        Route::resource('bigbets','BigBetsController');

        Route::resource('racingtracks','RacingTracksController');

        Route::resource('horses','HorsesController');

        Route::resource('livehorses','LiveHorsesController');

        Route::resource('distances','DistancesController');

        Route::resource('analysis','AnalysisController');

        Route::resource('analysistips','AnalysisTipsController');

        Route::get('/validatetip/{id}','AnalysisTipsController@validateTip')->name('validatetip');

        Route::resource('classes','AnalysisClassesController');

        Route::resource('chats','Chat\ChatsController');

        Route::get('analysisvalidated','AnalysisValidatedController@index')->name('analysisvalidated');

        Route::resource('horsepositions','HorsePositionsController');

        Route::resource('usertests','UserTestsController');

        // Route::get('/{chat_id}/messages','Chat\MessagesController@fetch');
        // Route::post('/{chat_id}/messages','Chat\MessagesController@sentMessage');

        Route::resource('tipstar','TipStarsController');
        Route::resource('racingtracksguides','RacingTrackGuidesController');

        Route::prefix('systeminfo')->group(function(){
            Route::get('/{key}','SystemInfosController@show');
            Route::put('/', 'SystemInfosController@update')->name('systeminfo.update');
        });

        Route::resource('startipvideos','StarTipVideosController');

        Route::resource('avulsevideos','AvulseVideosController');

        Route::resource('startipsprofits', 'StarTipsProfitsController');
    });
});

app/Http/Controllers/AvulseVideosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\AvulseVideo;

class AvulseVideosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $videos = AvulseVideo::latest()->paginate(10);

        return View('avulse_videos.index')->with('videos', $videos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('avulse_videos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $avulsevideo = new AvulseVideo;
        $avulsevideo->active = $request->has('active')? true: false;
        $avulsevideo->title = $request->input('title');
        $avulsevideo->msg = $request->input('msg');
        $avulsevideo->url = $request->input('url');
        $avulsevideo->createEmbedLink($request->input('url'));

        $avulsevideo->save();

        return redirect()->route('avulsevideos.index')->with('success','Video salvo');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $avulsevideo = AvulseVideo::find($id);

        return View('avulse_videos.edit')->with('video',$avulsevideo);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $avulsevideo = AvulseVideo::find($id);
        $avulsevideo->active = $request->has('active')? true: false;
        $avulsevideo->title = $request->input('title');
        $avulsevideo->msg = $request->input('msg');
        $avulsevideo->url = $request->input('url');
        $avulsevideo->createEmbedLink($request->input('url'));

        $avulsevideo->save();

        return redirect()->route('avulsevideos.index')->with('success','Video atualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $video = AvulseVideo::find($id);
        if($video){
            AvulseVideo::destroy($id);
        }
  
        return redirect()->route('avulsevideos.index')->with('success','Video removido');
    }
}

resources/views/avulse_videos/create.blade.php
@extends('layout.panel')

@section('content')
<div class="content-main " id="content-main">
  <div class="padding">
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="box-header">
            <h2>Novo Video Avulso</h2>
          </div>
          <div class="box-divider m-0"></div>
          <div class="box-body">
            <form action="{{route('avulsevideos.store')}}" method="post">
                {{ csrf_field() }}
              
              <div class="checkbox"><label class="ui-check ui-check-md"><input type="checkbox" name="active" id="active"> <i class="dark-white"></i> Ativo</label></div>
              
              <div class="form-group">
                <label>Titulo</label>
                <input type="text" name="title" class="form-control" placeholder="">
              </div>

              <div class="form-group">
                <label>Msg</label>
                <input type="text" name="msg" class="form-control" placeholder="msg">
              </div>

              <div class="form-group">
                <label>Video</label>
                <input type="text" name="url" class="form-control" placeholder="https://vimeo.com/29885705">
              </div>
            
              <button type="submit" class="btn primary">Salvar</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/avulse_videos/edit.blade.php
@extends('layout.panel')

@section('content')
<div class="content-main " id="content-main">
  <div class="padding">
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="box-header">
            <h2>Editar Video de Tips Star</h2>
          </div>
          <div class="box-divider m-0"></div>
          <div class="box-body">
            <form action="{{route('avulsevideos.update',['avulsevideo' => $video->id])}}" method="post">
                {{ csrf_field() }}

              <input type="hidden" name="_method" value="put">
              
              <div class="checkbox">
                <label class="ui-check ui-check-md">
                  <input type="checkbox" name="active" id="active" {{$video->active? 'checked' : ''}}> <i class="dark-white"></i> Ativo
                </label>
              </div>
              
              <div class="form-group">
                <label>Titulo</label>
                <input type="text" name="title" class="form-control" placeholder="" value="{{$video->title}}">
              </div>

              <div class="form-group">
                <label>Msg</label>
                <input type="text" name="msg" class="form-control" placeholder="msg" value="{{$video->msg}}">
              </div>

              <div class="form-group">
                <label>Video</label>
                <input type="text" name="url" class="form-control" placeholder="https://vimeo.com/29885705" value="{{$video->url}}"">
              </div>
            
              <button type="submit" class="btn primary">Salvar</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/avulse_videos/index.blade.php
@extends('layout.panel')

@section('content')

<style>
  
</style>
<div class="content-main " id="content-main">
  <div class="padding">
    <div class="row">
      <div class="col-lg-12">
        @if(Session::has('success'))
          <div class="alert green">
            <b>{{Session::get('success')}}</b>
          </div>
        @endif
      </div>
    </div>
    <div class="row align-items-stretch">
      <div class="col-sm-12">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Plataforma do Professor</a></li>
          <li class="breadcrumb-item active">Videos Avulsos</li>
        </ol>

        <div class="box">
          <div class="box-header">
              <h3>Avulse Video Info</h3>
          </div>
          <div class="box-body">
            <form  action="{{route('systeminfo.update')}}" method="post" id="system_info" data-key="avulse_videos">
              {{csrf_field()}}
              <div class="row">
                <div class="col-lg-11">
                  <div class="form-group">
                    <input type="hidden" name="key" value="">
                    <textarea class="form-control" name="val" placeholder="Info"></textarea>
                  </div>
                </div>
                <div class="col-lg-1">
                  <button class="btn btn-success btn-circle">
                    <i class="fas fa-check"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>

          <div class="box">
            <div class="box-header">
              <h3>Videos Avulsos</h3>
            </div>
            <div class="box-tool p-0" style="top: 5px !important;">
                <a href="{{route('avulsevideos.create')}}" class="btn btn-circle primary m-0"><i class="fa fa-plus"></i></a>
            </div>
            <div class="box-body p-0">
                <table id="" class="table v-middle p-0 m-0 box dataTable no-footer">
                    <thead>
                      <tr>
                        <tr>
                          <th align="center">Titulo</th>
                          <th align="center">Msg</th>
                          <th align="center">URL</th>
                          <th align="center" width="70px">Ações</th>
                        </tr>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($videos as $video)
                        <tr>
                            <td>{{$video->title}}</td>
                            <td>{{$video->msg}}</td>
                            <td>{{$video->url}}</td>
                            <td align="center">
                              <form action="{{route('avulsevideos.destroy',['avulsevideo'=>$video->id])}}" method="post">
                                {{csrf_field()}}
                                <input type="hidden" name="_method" value="delete">
                                <a href="{{route('avulsevideos.edit',['avulsevideo' => $video->id])}}" class="btn btn-primary btn-circle"><i class="fas fa-pencil-alt"></i></a>
                                <button type="submit" class="btn btn-danger btn-circle"><i class="fa fa-times"></i></button>
                              </form>
                            </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
            </div>
          </div> 
        
      </div>
    </div>
    <div class="row align-items-stretch">
      <div class="col-lg-12">
        {{$videos->links()}}
      </div>
    </div>
  </div>
</div>

@include('layout.elements.footer')
@endsection

@section('js')

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.2/dist/sweetalert2.all.min.js"></script>

<script>
    $(document).ready(function(){
      var key = $('form#system_info').data('key');
      $.get('/systeminfo/' + key, function(data){
        
        if(data.success){
          $('input[name=key]').val(data.data.key);
          $('textarea[name=val]').val(data.data.val);
        }
      });

      $('form#system_info').submit(function(evt){
        evt.preventDefault();
        console.log('salvando');
        $.ajax({
          'url' : $('form#system_info').attr('action'),
          'type' : 'PUT',
          'data' : $('form#system_info').serialize()
        })
        .done(function(result){
          console.log(result);
          if(result.success){
            Swal(
              'Informativo salvo!',
              '',
              'success'
            )
          }
        });
      });

    });
</script>
@endsection